name: Build Keyball46

on: push

jobs:

  build-keyball46-firmwares:
    name: Build Keyball46 firmwares
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Checkout qmk_firmware
      uses: actions/checkout@v2
      with:
        path: __qmk__
        repository: qmk/qmk_firmware
        submodules: recursive
        ref: '0.15.13'

    - name: Install a link to own source
      run: ln -s /home/runner/work/keyball/keyball/qmk_firmware/keyboards/keyball __qmk__/keyboards/keyball

    - name: Install git and pip
      run: sudo apt-get install -y git python3-pip

    - name: Install QMK CLI
      run: python3 -m pip install --user qmk

    - name: Setup QMK
      run: qmk setup --home __qmk__ --yes

    - run: qmk compile -j 4 -kb keyball/rev1/ball -km default
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/rev1/noball -km default
      continue-on-error: true

    - run: qmk compile -j 4 -kb keyball/rev1/ball -km test
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/rev1/noball -km test
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/rev1/ball -km test_Left
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/rev1/noball -km test_Left
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/rev1/ball -km test_Both
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/rev1/noball -km test_Both
      continue-on-error: true

    - run: qmk compile -j 4 -kb keyball/rev1/ball -km via
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/rev1/noball -km via
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/rev1/ball -km via_Left
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/rev1/noball -km via_Left
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/rev1/ball -km via_Both
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/rev1/noball -km via_Both
      continue-on-error: true

    - name: Archive firmwares
      uses: actions/upload-artifact@v2
      with:
        name: keyball46-firmwares
        path: __qmk__/*.hex
