name: Build Keyball46

on: push

jobs:

  build-keyball46-firmwares:
    name: Build Keyball46 firmwares
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup QMK firmware
      uses: ./.github/actions/setup-qmk

    - name: Install a link to own source
      run: ln -s $(pwd)/qmk_firmware/keyboards/keyball __qmk__/keyboards/keyball

    - run: qmk compile -j 4 -kb keyball/keyball46 -km default
      continue-on-error: true

    - run: qmk compile -j 4 -kb keyball/keyball46 -km test
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/keyball46 -km test_Left
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/keyball46 -km test_Both
      continue-on-error: true

    - run: qmk compile -j 4 -kb keyball/keyball46 -km via
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/keyball46 -km via_Left
      continue-on-error: true
    - run: qmk compile -j 4 -kb keyball/keyball46 -km via_Both
      continue-on-error: true

    - name: Archive firmwares
      uses: actions/upload-artifact@v2
      with:
        name: keyball46-firmwares
        path: __qmk__/*.hex
