name: Build Keyball61

on: push

jobs:

  build-keyball61-firmwares:
    name: Build Keyball61 firmwares
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup QMK firmware
      uses: ./.github/actions/setup-qmk

    - name: Install a link to own source
      run: ln -s $(pwd)/qmk_firmware/keyboards/keyball __qmk__/keyboards/keyball

    - run: qmk compile -j 4 -kb keyball/keyball61 -km default
      continue-on-error: true

    - run: qmk compile -j 4 -kb keyball/keyball61 -km test
      continue-on-error: true

    - run: qmk compile -j 4 -kb keyball/keyball61 -km via
      continue-on-error: true

    - name: Archive firmwares
      uses: actions/upload-artifact@v2
      with:
        name: keyball61-firmwares
        path: __qmk__/*.hex
